# Generated by Django 6.0.4 on 2026-04-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='iteration_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processrun',
            name='manual_latex_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processrun',
            name='max_iterations',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='stageresult',
            name='iteration_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stageresult',
            name='iteration_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stageresult',
            name='manual_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('awaiting_manual_input', 'Awaiting Manual Input'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
