# Generated by Django 6.0.4 on 2026-04-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0002_processrun_iteration_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processrun',
            name='max_iterations',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
