# Generated by Django 6.0.4 on 2026-04-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0003_alter_processrun_max_iterations'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='original_latex',
            field=models.TextField(blank=True),
        ),
    ]
